version: '2'

services:
  # Start the KillrVideo web UI on port 3000
  web:
    image: killrvideo/killrvideo-web:1.1.0
    ports:
    - "3000:3000"
    depends_on:
    - dse
    - etcd
    environment:
      SERVICE_3000_NAME: web
      KILLRVIDEO_ETCD: "etcd:2379"
  # The sample data generator
  generator:
    image: killrvideo/killrvideo-generator:1.1.0
    depends_on:
    - dse
    - etcd
    environment:
      KILLRVIDEO_ETCD: "etcd:2379"